# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20180319_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='student_time',
        ),
    ]
